GET http://localhost:3000/posts  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia3JpcyIsImlhdCI6MTc2OTY3NzI5NSwiZXhwIjoxNzY5Njc3MzU0fQ.JcCMgucotisdZI3V-2_Yadvk47BqOhIts_M8jq9V8BM
###
DELETE http://localhost:4000/logout 
Content-Type: application/json
{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia3JpcyIsImlhdCI6MTc2OTY3NjkzOH0.0EoOa9eYjx9DXHI8WYoN_7gVhhYWEj1V-zJuJT0MN_U"
}

###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoia3JpcyIsImlhdCI6MTc2OTY3NzIyOX0.cFAuVVakjljytQBqjocIwz4-4setqgmMt1bw9MTlYss"
}
###
POST http://localhost:4000/login
Content-Type: application/json

{
    "username":"kris"
}

#4,.3,.1,3,.1 .=>tokenValue